@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Article {
   Img: text
   Doc: text
   Code: text
   Name: text
   Desc: text
   ArticleTypeId: text
   BasePrice: numeric
   ArticleId: text
}
class ArticleArticleGroupType {
   ArticleGroupTypeId: text
   ArticleId: text
   Qta: numeric
   ArticleArticleGroupTypeId: text
}
class ArticleGroupType {
   Code: text
   Desc: text
   ProductionOrder: text
   ArticleGroupTypeId: text
}
class ArticleMachine {
   MachineId: text
   ArticleId: text
   Qta: numeric
   Note: text
   ArticleMachineId: text
}
class ArticleMachineType {
   ArticleId: text
   MachineTypeId: text
   Qta: numeric
   ArticleMachineTypeId: text
}
class ArticleType {
   Desc: text
   Code: text
   Year: integer
   ArticleTypeId: text
}
class Customer {
   Name: text
   Code: text
   CustomerId: text
}
class Invoice {
   Dt: text
   CustomerId: text
   Total: numeric
   InvoiceId: text
}
class InvoiceItem {
   Dt: text
   InvoiceId: text
   ArticleId: text
   MachineId: text
   Qta: numeric
   InvoiceItemId: text
}
class Machine {
   Nr: integer
   Year: integer
   Code: text
   Desc: text
   Img: text
   Doc: text
   MachineTypeId: text
   BasePrice: numeric
   Note: text
   ProductionOrder: text
   Address: text
   DtDelivery: text
   DtAcceptance: text
   DtEndWarranty: text
   DtStartWarranty: text
   MachineId: text
}
class MachineType {
   Desc: text
   Code: text
   Dt: text
   Nr: text
   Img: text
   Axes: integer
   Cnc: text
   Note: integer
   Spindles: integer
   MachineTypeId: text
}

Article                  -[#595959,plain]-^  ArticleType             : "ArticleTypeId"
ArticleArticleGroupType  -[#595959,plain]-^  Article                 : "ArticleId"
ArticleArticleGroupType  -[#595959,plain]-^  ArticleGroupType        : "ArticleGroupTypeId"
ArticleMachine           -[#595959,plain]-^  Article                 : "ArticleId"
ArticleMachine           -[#595959,plain]-^  Machine                 : "MachineId"
ArticleMachineType       -[#595959,plain]-^  Article                 : "ArticleId"
ArticleMachineType       -[#595959,plain]-^  MachineType             : "MachineTypeId"
Invoice                  -[#595959,plain]-^  Customer                : "CustomerId"
InvoiceItem              -[#595959,plain]-^  Article                 : "ArticleId"
InvoiceItem              -[#595959,plain]-^  Invoice                 : "InvoiceId"
InvoiceItem              -[#595959,plain]-^  Machine                 : "MachineId"
Machine                  -[#595959,plain]-^  MachineType             : "MachineTypeId"
@enduml
